<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\js\servicio\**" />
    <Content Remove="wwwroot\js\servicio\**" />
    <EmbeddedResource Remove="wwwroot\js\servicio\**" />
    <None Remove="wwwroot\js\servicio\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inventario.Entity\Inventario.Entity.csproj" />
    <ProjectReference Include="..\Inventario.IOC\Inventario.IOC.csproj" />
    <ProjectReference Include="..\Inventarios.BLL\Inventario.BLL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\img\" />
    <Folder Include="wwwroot\uploads\cuadro_comparativo\" />
    <Folder Include="wwwroot\uploads\diseños\" />
    <Folder Include="wwwroot\uploads\DocumentoSIAF\" />
    <Folder Include="wwwroot\uploads\Proveedor\" />
    <Folder Include="wwwroot\uploads\TablaApi\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
  </ItemGroup>

</Project>
