<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inventario.Entity\Inventario.Entity.csproj" />
    <ProjectReference Include="..\Inventario.IOC\Inventario.IOC.csproj" />
    <ProjectReference Include="..\Inventarios.BLL\Inventario.BLL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\img\" />
    <Folder Include="wwwroot\js\servicio\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
  </ItemGroup>

</Project>
